apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: webapp-app
    spec:
      containers:
      - name: webapp-container
        image: aniruddha530/simple-project 
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '500m'
            memory: '1Gi'
          requests:
            cpu: '500m'
            memory: '1Gi'
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
