apiVersion: v1
kind: Service
metadata:
  name: webapp-app
  labels:
    app: webapp-app
spec:
  selector:
    app: webapp-app
  type: LoadBalancer
  ports:
  - nodePort: 32750
    port: 8080
    targetPort: 8080
